# Generated by Django 5.0.6 on 2024-07-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
